### ISSUE TITLE
Can't use Kubernetes secrets instead of GitHub secrets

### ISSUE THREAD

**Issue by donohoel** [checkmarx-ts/checkmarx-github-action#230]
Hello,

I have created a workflow using the Checkmarx Full Scan GHA. Since our runners are self-hosted in Kubernetes, I wanted to add the cxUsername and cxPassword variables as secrets in Kubernetes so it's accessible from all repositories rather than having to add them as GitHub secrets to our many repositories. The relevant parts of the workflow are here:

```
env:
  GITHUB_REPOSITORY: ***
  CX_USER: $CHECKMARX_USERNAME
  CX_PASSWORD: $CHECKMARX_PASSWORD

jobs:
  run-full-checkmarx:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Checkmarx Full Scan
        uses: checkmarx-ts/checkmarx-github-action@v1.0.3
        with:
          cxServer: ***
          cxUsername: ${{ env.CX_USER }}
          cxPassword: ${{ env.CX_PASSWORD }}
          cxTeam: ***
          cxReportPDF: '***.pdf'
          cxProject: ${{ env.GITHUB_REPOSITORY }}
```

As with the cxProject variable where I have referred to a global variable and it has been accepted by the action, the login portion does not work. I have tried adding the variables as both global (above) and step envs but neither allows me to log into Checkmarx.

Any help/advice/corrections would be much appreciated 😊

**Comment by miguelfreitas93** [comment]
@donohoel according to this issue https://github.community/t/how-to-use-env-context/16975 it seems to be an issue with Github Action yml convertion.
You need to pass the environments to inside the step before using them, for example:
```yml
env:
  GITHUB_REPOSITORY: ***
  CX_USER: $CHECKMARX_USERNAME
  CX_PASSWORD: $CHECKMARX_PASSWORD

jobs:
  run-full-checkmarx:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Checkmarx Full Scan
        uses: checkmarx-ts/checkmarx-github-action@v1.0.5
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          CX_USER: ${{ env.CX_USER }}
          CX_PASSWORD: ${{ env.CX_PASSWORD }}
        with:
          cxServer: ***
          cxUsername: $CX_USER
          cxPassword: $CX_PASSWORD
          cxTeam: ***
          cxReportPDF: '***.pdf'
          cxProject: $GITHUB_REPOSITORY
```

Please also update the version from v1.0.3 to v1.0.5 or master
